from django.urls import path, re_path

from . import views

app_name = "shop"


urlpatterns = [
    path('', views.Home, name='home'),
    path('province/', views.get_province, name='province'),
    path('district/', views.get_district, name='district'),
    path('quienes-somos/', views.quienes_somos, name='quienes_somos'),
    path('como-comprar/', views.como_comprar, name='como_comprar'),
    path('contactanos/', views.contactanos, name='contactanos'),
    path('preguntas-frecuentes/', views.preguntas_frecuentes, name='preguntas_frecuentes'),
    path('legales/privacidad', views.legales_privacidad, name='legales_privacidad'),
    path('legales/terminos', views.legales_terminos, name='legales_terminos'),
    path('muestras/<slug:sample_slug>/medida-y-cantidad', views.StepOneView_Sample.as_view(), name='SampleDetail'),
    path('muestras/<slug:sample_slug>/subir-arte', views.StepTwoView_Sample.as_view(), name='UploadArt'),
    path('<slug:category_slug>/producto/<slug:product_slug>/elegir-diseno/', 
         views.template_gallery_view, 
         name='template_gallery'),
    path('<slug:c_slug>/<slug:product_slug>/medida-y-cantidad', views.StepOneView.as_view(), name='ProdDetail'),
    path('<slug:c_slug>/<slug:product_slug>/subir-arte', views.StepTwoView.as_view(), name='UploadArt'),
    #path('<slug:c_slug>/<slug:product_slug>', views.AddProduct, name='AddProduct'),
    #path('agregar-pack/', views.AddPack, name='AddPack'),
    #path('stickers-por-unidad/', views.AddUnitaryProduct, name='AddUnitaryProduct'),
    #path('<slug:c_slug>', views.ProdCatDetail, name='ProdCatDetail'),
    #path('make_review/', views.make_review_view, name='make_review_view'),
    #path('prices/', views.prices, name='prices'),
    path('email_confirmation_needed/', views.email_confirmation_needed, name='email_confirmation_needed'),
    re_path(r'^confirmacion-de-correo-electronico/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    path('tarjetas-presentacion/', views.TarjetasPresentacionListView.as_view(), name='tarjetas_presentacion'),
    path('ropa-bolsos/', views.ropa_bolsos, name='ropa_bolsos'),
    path('ropa-bolsos/<slug:category_slug>/', views.clothing_category, name='clothing_category'),
    path('ropa-bolsos/<slug:category_slug>/<slug:subcategory_slug>/', views.clothing_subcategory, name='clothing_subcategory'),
    path('ropa-bolsos/<slug:category_slug>/<slug:product_slug>/', views.clothing_product_detail, name='clothing_product_detail'),
    path('productos-promocionales/', views.productos_promocionales, name='productos_promocionales'),
    path('empaques/', views.EmpaquesListView.as_view(), name='empaques-list'),
    path('folletoss/', views.FolletosListView.as_view(), name='folletos-list'),
    path('posters/', views.PostersListView.as_view(), name='posters'),
    path('invitaciones-regalos/', views.invitaciones_regalos, name='invitaciones_regalos'),
    path('bodas/', views.bodas, name='bodas'),
    path('servicios-diseno/', views.servicios_diseno, name='servicios_diseno'),
    path('perfil/', views.profile_view, name='profile'),
    path('perfil/editar/', views.profile_edit_view, name='profile_edit'),
    path('agregar-producto-carrito/', views.add_product_to_cart, name='add_product_to_cart'),
    path('<slug:category_slug>/', views.category_view, name='category'),
    path('<slug:category_slug>/<slug:subcategory_slug>/', views.subcategory_view, name='subcategory'),
    path('<slug:category_slug>/producto/<slug:product_slug>/', views.product_detail_view, name='product_detail'),
    path('ropa-bolsos/<slug:category_slug>/', 
         views.clothing_category, 
         name='clothing_category'),
    path('ropa-bolsos/<slug:category_slug>/<slug:product_slug>/', 
         views.clothing_product_detail, 
         name='clothing_product_detail'),
    path('api/product-pricing/<str:product_slug>/<int:quantity>/', views.get_product_pricing, name='get_product_pricing'),
    path('api/product/<str:product_slug>/colors/', views.get_product_colors, name='get_product_colors'),
    path('api/clothing/add-to-cart/', views.add_clothing_to_cart, name='add_clothing_to_cart'),
]
