# Generated by Django 4.2.15 on 2025-12-11 13:35

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('slug', models.SlugField(help_text='Identificador único de la categoría', max_length=250, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=250, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('image_url', models.CharField(blank=True, max_length=500, verbose_name='URL de imagen')),
                ('icon', models.CharField(blank=True, help_text='Clase de Font Awesome, ej: fa-tshirt', max_length=50)),
                ('display_order', models.IntegerField(default=0, help_text='Menor número aparece primero', verbose_name='Orden de visualización')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('seasonal', 'Temporal')], default='active', max_length=20, verbose_name='Estado')),
                ('category_type', models.CharField(choices=[('quality_tiers', 'Niveles de Calidad'), ('product_types', 'Tipos de Producto'), ('formats', 'Formatos de Entrega'), ('services', 'Servicios'), ('occasions', 'Ocasiones'), ('standard', 'Estándar')], default='standard', help_text='Define cómo se renderiza esta categoría en el frontend', max_length=20, verbose_name='Tipo de Categoría')),
                ('custom_template', models.CharField(blank=True, help_text='Nombre del template a usar, ej: shop/ropa_bolsos.html', max_length=100, verbose_name='Template personalizado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Empaque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='empaques')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='etiquetas')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Folleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='folletos')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Peru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('distrito', models.CharField(max_length=100)),
                ('costo_despacho_con_recojo', models.IntegerField(default=15)),
                ('costo_despacho_sin_recojo', models.IntegerField(default=15)),
                ('dias_despacho', models.IntegerField(default=4)),
            ],
        ),
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='posters')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('slug', models.SlugField(help_text='Identificador único del producto', max_length=250, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, verbose_name='Nombre del Producto')),
                ('sku', models.CharField(help_text='Código único del producto', max_length=50, unique=True, verbose_name='SKU')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('short_description', models.CharField(blank=True, max_length=200, verbose_name='Descripción corta')),
                ('base_image_url', models.CharField(blank=True, max_length=500, verbose_name='URL de imagen principal')),
                ('hover_image_url', models.CharField(blank=True, max_length=500, verbose_name='URL de imagen hover')),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio base')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio oferta')),
                ('min_quantity', models.IntegerField(default=1, verbose_name='Cantidad mínima')),
                ('material', models.CharField(blank=True, help_text='Material del producto o marca para ropa', max_length=100, verbose_name='Material/Marca')),
                ('weight', models.CharField(blank=True, max_length=50, verbose_name='Peso')),
                ('features', models.TextField(blank=True, help_text='Para ropa: genero:unisex,cuello:cuello_redondo', verbose_name='Características')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacado')),
                ('is_new', models.BooleanField(default=False, verbose_name='Nuevo')),
                ('is_bestseller', models.BooleanField(default=False, verbose_name='Más vendido')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('seasonal', 'Temporal')], default='active', max_length=20, verbose_name='Estado')),
                ('display_order', models.IntegerField(default=0, verbose_name='Orden de visualización')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'products',
                'ordering': ['-is_featured', '-is_bestseller', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Identificador único: color, size, material, finish, cassette, etc.', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Nombre que se muestra al usuario: Color, Talla, Material, etc.', max_length=100, verbose_name='Nombre visible')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Orden de visualización')),
                ('is_required', models.BooleanField(default=True, help_text='Si es True, el usuario debe seleccionar una opción', verbose_name='Es requerido')),
                ('selection_type', models.CharField(choices=[('single', 'Única'), ('multiple', 'Múltiple')], default='single', help_text='Única: solo un valor. Múltiple: varios valores posibles', max_length=10, verbose_name='Tipo de selección')),
            ],
            options={
                'verbose_name': 'Opción de Producto',
                'verbose_name_plural': 'Opciones de Productos',
                'db_table': 'product_options',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductOptionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Identificador interno: rojo, azul, xs, s, lona-13oz', max_length=100, verbose_name='Valor interno')),
                ('display_name', models.CharField(blank=True, help_text="Nombre mostrado al usuario. Si está vacío, usa 'value'", max_length=100, verbose_name='Nombre visible')),
                ('image', models.ImageField(blank=True, help_text='Para colores: muestra del color. Para materiales: textura', null=True, upload_to='option_images/', verbose_name='Imagen/Muestra')),
                ('hex_code', models.CharField(blank=True, help_text='Solo para colores: #FF5733', max_length=7, verbose_name='Código Hex')),
                ('additional_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Costo extra al seleccionar esta opción', max_digits=10, verbose_name='Precio adicional')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Orden de visualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='shop.productoption', verbose_name='Tipo de Opción')),
            ],
            options={
                'verbose_name': 'Valor de Opción',
                'verbose_name_plural': 'Valores de Opciones',
                'db_table': 'product_option_values',
                'ordering': ['option', 'display_order', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='TarjetaPresentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tarjetas_presentacion')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('type', models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium'), ('deluxe', 'Deluxe')], default='standard', max_length=20)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('slug', models.SlugField(help_text='Identificador único de la subcategoría', max_length=250, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=250, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('image_url', models.CharField(blank=True, max_length=500, verbose_name='URL de imagen')),
                ('icon', models.CharField(blank=True, help_text='Clase de Font Awesome, ej: fa-tshirt', max_length=50)),
                ('display_order', models.IntegerField(default=0, verbose_name='Orden de visualización')),
                ('display_style', models.CharField(choices=[('tab', 'Tabs Horizontales'), ('circle', 'Círculos con Imagen'), ('card', 'Cards con Imagen'), ('vertical_card', 'Cards Verticales')], default='card', help_text='Cómo se muestra esta subcategoría en el frontend', max_length=20, verbose_name='Estilo de Visualización')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo')], default='active', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='shop.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Subcategoría',
                'verbose_name_plural': 'Subcategorías',
                'db_table': 'subcategories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('dni', models.CharField(blank=True, max_length=30)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('shipping_address1', models.CharField(max_length=100)),
                ('reference', models.CharField(max_length=100)),
                ('shipping_department', models.CharField(max_length=100)),
                ('shipping_province', models.CharField(max_length=100)),
                ('shipping_district', models.CharField(max_length=100)),
                ('photo', models.ImageField(default='profile_pics/default_profile_pic_white.png', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Orden en que aparece esta opción en el producto', verbose_name='Orden de visualización')),
                ('available_values', models.ManyToManyField(blank=True, help_text='Si está vacío, todos los valores activos de la opción están disponibles', related_name='product_variants', to='shop.productoptionvalue', verbose_name='Valores disponibles')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_variants', to='shop.productoption', verbose_name='Tipo de Opción')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_options', to='shop.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Variante de Producto',
                'verbose_name_plural': 'Variantes de Productos',
                'db_table': 'product_variants',
                'ordering': ['product', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=500, verbose_name='URL de imagen')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
                ('option_value', models.ForeignKey(blank=True, help_text='Opcional: asociar esta imagen a un color/material específico', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_images', to='shop.productoptionvalue', verbose_name='Valor de opción')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product')),
            ],
            options={
                'verbose_name': 'Imagen de Producto',
                'verbose_name_plural': 'Imágenes de Productos',
                'db_table': 'product_images',
                'ordering': ['display_order'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.subcategory', verbose_name='Subcategoría'),
        ),
        migrations.CreateModel(
            name='PriceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_quantity', models.IntegerField(verbose_name='Cantidad mínima')),
                ('max_quantity', models.IntegerField(verbose_name='Cantidad máxima')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('discount_percentage', models.IntegerField(default=0, verbose_name='Porcentaje de descuento')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_tiers', to='shop.product')),
            ],
            options={
                'verbose_name': 'Nivel de Precio',
                'verbose_name_plural': 'Niveles de Precios',
                'db_table': 'price_tiers',
                'ordering': ['product', 'min_quantity'],
            },
        ),
        migrations.CreateModel(
            name='DesignTemplate',
            fields=[
                ('slug', models.SlugField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Template')),
                ('description', models.TextField(blank=True)),
                ('thumbnail_url', models.CharField(max_length=500, verbose_name='URL Miniatura')),
                ('preview_url', models.CharField(blank=True, max_length=500, verbose_name='URL Preview')),
                ('is_popular', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_templates', to='shop.category')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_templates', to='shop.subcategory')),
            ],
            options={
                'verbose_name': 'Template de Diseño',
                'verbose_name_plural': 'Templates de Diseño',
                'db_table': 'design_templates',
                'ordering': ['-is_popular', 'display_order', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['status'], name='categories_status_dda6e6_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['display_order'], name='categories_display_d2cb49_idx'),
        ),
        migrations.AddIndex(
            model_name='subcategory',
            index=models.Index(fields=['category', 'display_order'], name='subcategori_categor_730358_idx'),
        ),
        migrations.AddIndex(
            model_name='subcategory',
            index=models.Index(fields=['status'], name='subcategori_status_05cd3a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'option')},
        ),
        migrations.AlterUniqueTogether(
            name='productoptionvalue',
            unique_together={('option', 'value')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'status'], name='products_categor_29e98f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['subcategory', 'status'], name='products_subcate_34ad01_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='products_sku_fe2039_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_featured', 'is_bestseller'], name='products_is_feat_3103d9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pricetier',
            unique_together={('product', 'min_quantity')},
        ),
    ]
