# Generated by Django 4.2.15 on 2025-11-26 22:50

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('slug', models.SlugField(help_text='Identificador único de la categoría', max_length=250, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=250, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('image_url', models.CharField(blank=True, max_length=500, verbose_name='URL de imagen')),
                ('display_order', models.IntegerField(default=0, help_text='Menor número aparece primero', verbose_name='Orden de visualización')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('seasonal', 'Temporal')], default='active', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClothingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='clothing/categories/')),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Clothing Category',
                'verbose_name_plural': 'Clothing Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClothingColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('hex_code', models.CharField(help_text='Color hex code, e.g., #FF5733', max_length=7)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClothingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250)),
                ('sku', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('short_description', models.CharField(blank=True, max_length=200)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_quantity', models.IntegerField(default=1)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='clothing/products/')),
                ('hover_image', models.ImageField(blank=True, null=True, upload_to='clothing/products/')),
                ('material', models.CharField(blank=True, max_length=100)),
                ('weight', models.CharField(blank=True, max_length=50)),
                ('features', models.TextField(blank=True, help_text='Comma-separated features')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=False)),
                ('is_bestseller', models.BooleanField(default=False)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('available_colors', models.ManyToManyField(blank=True, related_name='products', to='shop.clothingcolor')),
            ],
            options={
                'verbose_name': 'Clothing Product',
                'verbose_name_plural': 'Clothing Products',
                'ordering': ['-is_featured', '-is_bestseller', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClothingSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('display_name', models.CharField(max_length=50)),
                ('size_type', models.CharField(choices=[('clothing', 'Ropa'), ('hat', 'Gorras'), ('bag', 'Bolsas')], default='clothing', max_length=20)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['size_type', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Empaque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='empaques')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='etiquetas')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Folleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='folletos')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Peru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('distrito', models.CharField(max_length=100)),
                ('costo_despacho_con_recojo', models.IntegerField(default=15)),
                ('costo_despacho_sin_recojo', models.IntegerField(default=15)),
                ('dias_despacho', models.IntegerField(default=4)),
            ],
        ),
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='posters')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('slug', models.SlugField(help_text='Identificador único del producto', max_length=250, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, verbose_name='Nombre del Producto')),
                ('sku', models.CharField(help_text='Código único del producto', max_length=50, unique=True, verbose_name='SKU')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('base_image_url', models.CharField(blank=True, max_length=500, verbose_name='URL de imagen base')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('seasonal', 'Temporal')], default='active', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_products', to='shop.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'catalog_product',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TarjetaPresentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tarjetas_presentacion')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VariantType',
            fields=[
                ('slug', models.SlugField(help_text='Identificador único del tipo de variante', max_length=250, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=250, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_required', models.BooleanField(default=False, help_text='Si es true, el usuario debe seleccionar una opción', verbose_name='Es requerido')),
                ('allows_multiple', models.BooleanField(default=False, help_text='Si permite seleccionar múltiples opciones', verbose_name='Permite múltiples')),
                ('display_order', models.IntegerField(default=0, verbose_name='Orden de visualización')),
                ('applies_to', models.CharField(blank=True, help_text='Categorías o tipos de productos a los que aplica', max_length=100, null=True, verbose_name='Aplica a')),
            ],
            options={
                'verbose_name': 'Tipo de Variante',
                'verbose_name_plural': 'Tipos de Variantes',
                'db_table': 'variant_type',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['display_order'], name='variant_typ_display_06b001_idx')],
            },
        ),
        migrations.CreateModel(
            name='VariantOption',
            fields=[
                ('slug', models.SlugField(help_text='Identificador único de la opción', max_length=250, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('additional_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Costo extra por seleccionar esta opción', max_digits=10, verbose_name='Precio adicional')),
                ('image_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='URL de imagen')),
                ('display_order', models.IntegerField(default=0, verbose_name='Orden de visualización')),
                ('variant_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='shop.varianttype', verbose_name='Tipo de Variante')),
            ],
            options={
                'verbose_name': 'Opción de Variante',
                'verbose_name_plural': 'Opciones de Variantes',
                'db_table': 'variant_option',
                'ordering': ['variant_type', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('slug', models.SlugField(help_text='Identificador único de la subcategoría', max_length=250, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=250, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('image_url', models.CharField(blank=True, max_length=500, verbose_name='URL de imagen')),
                ('display_order', models.IntegerField(default=0, verbose_name='Orden de visualización')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='shop.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Subcategoría',
                'verbose_name_plural': 'Subcategorías',
                'db_table': 'catalog_subcategory',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('dni', models.CharField(blank=True, max_length=30)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('shipping_address1', models.CharField(max_length=100)),
                ('reference', models.CharField(max_length=100)),
                ('shipping_department', models.CharField(max_length=100)),
                ('shipping_province', models.CharField(max_length=100)),
                ('shipping_district', models.CharField(max_length=100)),
                ('photo', models.ImageField(default='profile_pics/default_profile_pic_white.png', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariantType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_variant_types', to='shop.product', verbose_name='Producto')),
                ('variant_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_variant_types', to='shop.varianttype', verbose_name='Tipo de Variante')),
            ],
            options={
                'verbose_name': 'Variante de Producto',
                'verbose_name_plural': 'Variantes de Productos',
                'db_table': 'product_variant_type',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_products', to='shop.subcategory', verbose_name='Subcategoría'),
        ),
        migrations.CreateModel(
            name='PriceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_quantity', models.IntegerField(help_text='Cantidad mínima para este precio', verbose_name='Cantidad mínima')),
                ('max_quantity', models.IntegerField(help_text='Cantidad máxima para este precio', verbose_name='Cantidad máxima')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Precio por unidad en este rango', max_digits=10, verbose_name='Precio unitario')),
                ('discount_percentage', models.IntegerField(default=0, help_text='Descuento aplicado respecto al precio base', verbose_name='Porcentaje de descuento')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_tiers', to='shop.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Nivel de Precio',
                'verbose_name_plural': 'Niveles de Precios',
                'db_table': 'price_tier',
                'ordering': ['product', 'min_quantity'],
            },
        ),
        migrations.CreateModel(
            name='ClothingSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='clothing/subcategories/')),
                ('order', models.IntegerField(default=0)),
                ('available', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothing_subcategories', to='shop.clothingcategory')),
            ],
            options={
                'verbose_name': 'Clothing SubCategory',
                'verbose_name_plural': 'Clothing SubCategories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClothingProductPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_quantity', models.IntegerField()),
                ('max_quantity', models.IntegerField(blank=True, null=True)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_tiers', to='shop.clothingproduct')),
            ],
            options={
                'ordering': ['min_quantity'],
            },
        ),
        migrations.CreateModel(
            name='ClothingProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='clothing/products/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.clothingcolor')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.clothingproduct')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='clothingproduct',
            name='available_sizes',
            field=models.ManyToManyField(blank=True, related_name='products', to='shop.clothingsize'),
        ),
        migrations.AddField(
            model_name='clothingproduct',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.clothingcategory'),
        ),
        migrations.AddField(
            model_name='clothingproduct',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.clothingsubcategory'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['status'], name='categories_status_dda6e6_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['display_order'], name='categories_display_d2cb49_idx'),
        ),
        migrations.AddIndex(
            model_name='variantoption',
            index=models.Index(fields=['variant_type', 'display_order'], name='variant_opt_variant_5326e6_idx'),
        ),
        migrations.AddIndex(
            model_name='subcategory',
            index=models.Index(fields=['category', 'display_order'], name='catalog_sub_categor_f0caa9_idx'),
        ),
        migrations.AddIndex(
            model_name='productvarianttype',
            index=models.Index(fields=['product'], name='product_var_product_b316f1_idx'),
        ),
        migrations.AddIndex(
            model_name='productvarianttype',
            index=models.Index(fields=['variant_type'], name='product_var_variant_71ae7f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productvarianttype',
            unique_together={('product', 'variant_type')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'status'], name='catalog_pro_categor_da0f0a_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['subcategory', 'status'], name='catalog_pro_subcate_1088a6_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='catalog_pro_sku_2c4c34_idx'),
        ),
        migrations.AddIndex(
            model_name='pricetier',
            index=models.Index(fields=['product', 'min_quantity'], name='price_tier_product_064add_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pricetier',
            unique_together={('product', 'min_quantity')},
        ),
        migrations.AlterUniqueTogether(
            name='clothingsubcategory',
            unique_together={('category', 'slug')},
        ),
    ]
