# Generated by Django 4.2.15 on 2025-11-27 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pricetier',
            new_name='price_tiers_product_010299_idx',
            old_name='price_tier_product_064add_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='products_categor_29e98f_idx',
            old_name='catalog_pro_categor_da0f0a_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='products_subcate_34ad01_idx',
            old_name='catalog_pro_subcate_1088a6_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='products_sku_fe2039_idx',
            old_name='catalog_pro_sku_2c4c34_idx',
        ),
        migrations.RenameIndex(
            model_name='productvarianttype',
            new_name='product_var_product_1a593c_idx',
            old_name='product_var_product_b316f1_idx',
        ),
        migrations.RenameIndex(
            model_name='productvarianttype',
            new_name='product_var_variant_00ad01_idx',
            old_name='product_var_variant_71ae7f_idx',
        ),
        migrations.RenameIndex(
            model_name='subcategory',
            new_name='subcategori_categor_730358_idx',
            old_name='catalog_sub_categor_f0caa9_idx',
        ),
        migrations.RenameIndex(
            model_name='variantoption',
            new_name='variant_opt_variant_865351_idx',
            old_name='variant_opt_variant_5326e6_idx',
        ),
        migrations.RenameIndex(
            model_name='varianttype',
            new_name='variant_typ_display_24dca8_idx',
            old_name='variant_typ_display_06b001_idx',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.subcategory', verbose_name='Subcategoría'),
        ),
        migrations.AlterModelTable(
            name='pricetier',
            table='price_tiers',
        ),
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
        migrations.AlterModelTable(
            name='productvarianttype',
            table='product_variant_types',
        ),
        migrations.AlterModelTable(
            name='subcategory',
            table='subcategories',
        ),
        migrations.AlterModelTable(
            name='variantoption',
            table='variant_options',
        ),
        migrations.AlterModelTable(
            name='varianttype',
            table='variant_types',
        ),
    ]
