# Generated by Django 4.2.15 on 2025-12-18 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Empaque',
        ),
        migrations.DeleteModel(
            name='Etiqueta',
        ),
        migrations.DeleteModel(
            name='Folleto',
        ),
        migrations.DeleteModel(
            name='Poster',
        ),
        migrations.DeleteModel(
            name='TarjetaPresentacion',
        ),
    ]
