# Generated by Django 5.1.7 on 2025-11-27 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_price_tier_product_064add_idx_price_tiers_product_010299_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjetapresentacion',
            name='type',
            field=models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium'), ('deluxe', 'Deluxe')], default='standard', max_length=20, verbose_name='Tipo'),
        ),
    ]
