# Generated by Django 5.2.9 on 2026-01-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='design_image',
            field=models.ImageField(blank=True, help_text='Imagen que muestra el diseño final', null=True, upload_to='pre_designed_mockups/', verbose_name='Mockup del diseño'),
        ),
        migrations.AddField(
            model_name='product',
            name='design_reference',
            field=models.CharField(blank=True, help_text='Ej: Mateo 17:20', max_length=100, verbose_name='Referencia'),
        ),
        migrations.AddField(
            model_name='product',
            name='design_text',
            field=models.TextField(blank=True, help_text='Frase o texto estampado predefinido', verbose_name='Texto del diseño'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_pre_designed',
            field=models.BooleanField(default=False, help_text='Si es True, el usuario no necesita subir diseño ni elegir template.', verbose_name='Es pre-diseñado'),
        ),
    ]
