# Generated by Django 4.2.15 on 2025-12-01 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_tarjetapresentacion_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('quality_tiers', 'Niveles de Calidad'), ('product_types', 'Tipos de Producto'), ('formats', 'Formatos de Entrega'), ('services', 'Servicios'), ('occasions', 'Ocasiones'), ('standard', 'Estándar')], default='standard', help_text='Define cómo se renderiza esta categoría en el frontend', max_length=20, verbose_name='Tipo de Categoría'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='display_style',
            field=models.CharField(choices=[('tab', 'Tabs Horizontales'), ('circle', 'Círculos con Imagen'), ('card', 'Cards con Imagen'), ('vertical_card', 'Cards Verticales')], default='card', help_text='Cómo se muestra esta subcategoría en el frontend', max_length=20, verbose_name='Estilo de Visualización'),
        ),
        migrations.CreateModel(
            name='DesignTemplate',
            fields=[
                ('slug', models.SlugField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Template')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('thumbnail_url', models.CharField(help_text='Imagen pequeña para grid', max_length=500, verbose_name='URL Miniatura')),
                ('preview_url', models.CharField(blank=True, help_text='Imagen grande para vista previa', max_length=500, verbose_name='URL Preview')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Es Popular')),
                ('is_new', models.BooleanField(default=False, verbose_name='Es Nuevo')),
                ('display_order', models.IntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_templates', to='shop.category', verbose_name='Categoría')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_templates', to='shop.subcategory', verbose_name='Subcategoría')),
            ],
            options={
                'verbose_name': 'Template de Diseño',
                'verbose_name_plural': 'Templates de Diseño',
                'db_table': 'design_templates',
                'ordering': ['-is_popular', 'display_order', 'name'],
            },
        ),
    ]
