# Generated by Django 4.2.15 on 2025-12-03 15:52

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_category_category_type_subcategory_display_style_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('slug', models.SlugField(unique=True)),
                ('hex_code', models.CharField(help_text='Código hex, ej: #FF5733', max_length=7)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Color de Producto',
                'verbose_name_plural': 'Colores de Productos',
                'db_table': 'product_colors',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=500, verbose_name='URL de imagen')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Imagen de Producto',
                'verbose_name_plural': 'Imágenes de Productos',
                'db_table': 'product_images',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('display_name', models.CharField(max_length=50)),
                ('size_type', models.CharField(choices=[('clothing', 'Ropa'), ('hat', 'Gorras'), ('bag', 'Bolsas'), ('universal', 'Universal')], default='clothing', max_length=20)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Talla de Producto',
                'verbose_name_plural': 'Tallas de Productos',
                'db_table': 'product_sizes',
                'ordering': ['size_type', 'display_order'],
            },
        ),
        migrations.RemoveField(
            model_name='clothingproduct',
            name='available_colors',
        ),
        migrations.RemoveField(
            model_name='clothingproduct',
            name='available_sizes',
        ),
        migrations.RemoveField(
            model_name='clothingproduct',
            name='category',
        ),
        migrations.RemoveField(
            model_name='clothingproduct',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='clothingproductimage',
            name='color',
        ),
        migrations.RemoveField(
            model_name='clothingproductimage',
            name='product',
        ),
        migrations.RemoveField(
            model_name='clothingproductpricing',
            name='product',
        ),
        migrations.AlterUniqueTogether(
            name='clothingsubcategory',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='clothingsubcategory',
            name='category',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-is_featured', '-is_bestseller', 'name'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.RemoveIndex(
            model_name='pricetier',
            name='price_tiers_product_010299_idx',
        ),
        migrations.RemoveIndex(
            model_name='productvarianttype',
            name='product_var_product_1a593c_idx',
        ),
        migrations.RemoveIndex(
            model_name='productvarianttype',
            name='product_var_variant_00ad01_idx',
        ),
        migrations.RemoveIndex(
            model_name='variantoption',
            name='variant_opt_variant_865351_idx',
        ),
        migrations.RemoveIndex(
            model_name='varianttype',
            name='variant_typ_display_24dca8_idx',
        ),
        migrations.AddField(
            model_name='category',
            name='custom_template',
            field=models.CharField(blank=True, help_text='Nombre del template a usar, ej: shop/ropa_bolsos.html', max_length=100, verbose_name='Template personalizado'),
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text='Clase de Font Awesome, ej: fa-tshirt', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio base'),
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.TextField(blank=True, help_text='Características separadas por coma', verbose_name='Características'),
        ),
        migrations.AddField(
            model_name='product',
            name='hover_image_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='URL de imagen hover'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_bestseller',
            field=models.BooleanField(default=False, verbose_name='Más vendido'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Destacado'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='Nuevo'),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, max_length=100, verbose_name='Material'),
        ),
        migrations.AddField(
            model_name='product',
            name='min_quantity',
            field=models.IntegerField(default=1, verbose_name='Cantidad mínima'),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio oferta'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, max_length=200, verbose_name='Descripción corta'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.CharField(blank=True, max_length=50, verbose_name='Peso'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='icon',
            field=models.CharField(blank=True, help_text='Clase de Font Awesome, ej: fa-tshirt', max_length=50),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='status',
            field=models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo')], default='active', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('seasonal', 'Temporal')], default='active', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='designtemplate',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_templates', to='shop.category'),
        ),
        migrations.AlterField(
            model_name='designtemplate',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='designtemplate',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='designtemplate',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='designtemplate',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='designtemplate',
            name='preview_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='URL Preview'),
        ),
        migrations.AlterField(
            model_name='designtemplate',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_templates', to='shop.subcategory'),
        ),
        migrations.AlterField(
            model_name='designtemplate',
            name='thumbnail_url',
            field=models.CharField(max_length=500, verbose_name='URL Miniatura'),
        ),
        migrations.AlterField(
            model_name='pricetier',
            name='discount_percentage',
            field=models.IntegerField(default=0, verbose_name='Porcentaje de descuento'),
        ),
        migrations.AlterField(
            model_name='pricetier',
            name='max_quantity',
            field=models.IntegerField(verbose_name='Cantidad máxima'),
        ),
        migrations.AlterField(
            model_name='pricetier',
            name='min_quantity',
            field=models.IntegerField(verbose_name='Cantidad mínima'),
        ),
        migrations.AlterField(
            model_name='pricetier',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_tiers', to='shop.product'),
        ),
        migrations.AlterField(
            model_name='pricetier',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario'),
        ),
        migrations.AlterField(
            model_name='product',
            name='base_image_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='URL de imagen principal'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('seasonal', 'Temporal')], default='active', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='productvarianttype',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_variant_types', to='shop.product'),
        ),
        migrations.AlterField(
            model_name='productvarianttype',
            name='variant_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_variant_types', to='shop.varianttype'),
        ),
        migrations.AlterField(
            model_name='tarjetapresentacion',
            name='type',
            field=models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium'), ('deluxe', 'Deluxe')], default='standard', max_length=20),
        ),
        migrations.AlterField(
            model_name='variantoption',
            name='additional_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Precio adicional'),
        ),
        migrations.AlterField(
            model_name='variantoption',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='variantoption',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='variantoption',
            name='slug',
            field=models.SlugField(max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='variantoption',
            name='variant_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='shop.varianttype'),
        ),
        migrations.AlterField(
            model_name='varianttype',
            name='allows_multiple',
            field=models.BooleanField(default=False, verbose_name='Permite múltiples'),
        ),
        migrations.AlterField(
            model_name='varianttype',
            name='applies_to',
            field=models.CharField(blank=True, help_text='Categorías o tipos de productos', max_length=100, null=True, verbose_name='Aplica a'),
        ),
        migrations.AlterField(
            model_name='varianttype',
            name='is_required',
            field=models.BooleanField(default=False, verbose_name='Es requerido'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_featured', 'is_bestseller'], name='products_is_feat_3103d9_idx'),
        ),
        migrations.AddIndex(
            model_name='subcategory',
            index=models.Index(fields=['status'], name='subcategori_status_05cd3a_idx'),
        ),
        migrations.DeleteModel(
            name='ClothingCategory',
        ),
        migrations.DeleteModel(
            name='ClothingColor',
        ),
        migrations.DeleteModel(
            name='ClothingProduct',
        ),
        migrations.DeleteModel(
            name='ClothingProductImage',
        ),
        migrations.DeleteModel(
            name='ClothingProductPricing',
        ),
        migrations.DeleteModel(
            name='ClothingSize',
        ),
        migrations.DeleteModel(
            name='ClothingSubCategory',
        ),
        migrations.AddField(
            model_name='productimage',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_images', to='shop.productcolor'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='available_colors',
            field=models.ManyToManyField(blank=True, related_name='products', to='shop.productcolor', verbose_name='Colores disponibles'),
        ),
        migrations.AddField(
            model_name='product',
            name='available_sizes',
            field=models.ManyToManyField(blank=True, related_name='products', to='shop.productsize', verbose_name='Tallas disponibles'),
        ),
    ]
