# Generated by Django 4.2.15 on 2025-12-04 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_productcolor_productimage_productsize_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-is_featured', '-is_bestseller', 'display_order', 'name'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AddField(
            model_name='product',
            name='display_order',
            field=models.IntegerField(default=0, verbose_name='Orden de visualización'),
        ),
        migrations.AlterField(
            model_name='product',
            name='features',
            field=models.TextField(blank=True, help_text='Para ropa: genero:unisex,cuello:cuello_redondo,manga:manga_corta', verbose_name='Características'),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, help_text='Material del producto o marca para ropa', max_length=100, verbose_name='Material/Marca'),
        ),
    ]
