# Generated by Django 4.2.15 on 2025-11-26 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_empaque_etiqueta_folleto_poster_tarjetapresentacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='clothing/categories/')),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Clothing Category',
                'verbose_name_plural': 'Clothing Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClothingColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('hex_code', models.CharField(help_text='Color hex code, e.g., #FF5733', max_length=7)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClothingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250)),
                ('sku', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('short_description', models.CharField(blank=True, max_length=200)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_quantity', models.IntegerField(default=1)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='clothing/products/')),
                ('hover_image', models.ImageField(blank=True, null=True, upload_to='clothing/products/')),
                ('material', models.CharField(blank=True, max_length=100)),
                ('weight', models.CharField(blank=True, max_length=50)),
                ('features', models.TextField(blank=True, help_text='Comma-separated features')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=False)),
                ('is_bestseller', models.BooleanField(default=False)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('available_colors', models.ManyToManyField(blank=True, related_name='products', to='shop.clothingcolor')),
            ],
            options={
                'verbose_name': 'Clothing Product',
                'verbose_name_plural': 'Clothing Products',
                'ordering': ['-is_featured', '-is_bestseller', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClothingSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('display_name', models.CharField(max_length=50)),
                ('size_type', models.CharField(choices=[('clothing', 'Ropa'), ('hat', 'Gorras'), ('bag', 'Bolsas')], default='clothing', max_length=20)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['size_type', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ClothingSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='clothing/subcategories/')),
                ('order', models.IntegerField(default=0)),
                ('available', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='shop.clothingcategory')),
            ],
            options={
                'verbose_name': 'Clothing SubCategory',
                'verbose_name_plural': 'Clothing SubCategories',
                'ordering': ['order', 'name'],
                'unique_together': {('category', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='ClothingProductPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_quantity', models.IntegerField()),
                ('max_quantity', models.IntegerField(blank=True, null=True)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_tiers', to='shop.clothingproduct')),
            ],
            options={
                'ordering': ['min_quantity'],
            },
        ),
        migrations.CreateModel(
            name='ClothingProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='clothing/products/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.clothingcolor')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.clothingproduct')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='clothingproduct',
            name='available_sizes',
            field=models.ManyToManyField(blank=True, related_name='products', to='shop.clothingsize'),
        ),
        migrations.AddField(
            model_name='clothingproduct',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.clothingcategory'),
        ),
        migrations.AddField(
            model_name='clothingproduct',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.clothingsubcategory'),
        ),
    ]
