# Generated by Django 4.2.15 on 2025-12-11 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.CharField(blank=True, max_length=250)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Cart',
                'ordering': ['date_added'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, choices=[('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5'), ('A6', 'A6'), ('A7', 'A7'), ('medio-oficio', 'Medio oficio'), ('oficio', 'Oficio'), ('carta', 'Carta'), ('4x8', '4 x 8'), ('5x10', '5 x 10'), ('5x14', '5 x 14'), ('5x17', '5 x 17'), ('3x5', '3 x 5'), ('10x14', '10 x 14'), ('10x17', '10 x 17'), ('10x21', '10 x 21'), ('14x21', '14 x 21')], max_length=20, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('design_file', models.FileField(blank=True, max_length=500, null=True, upload_to='designs/%Y/%m/%d/')),
                ('comment', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True, verbose_name='Color')),
                ('color_image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de imagen del color')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('step_two_complete', models.BooleanField(default=False)),
                ('logo_file', models.FileField(blank=True, max_length=500, null=True, upload_to='logos/%Y/%m/%d/', verbose_name='Logo de empresa')),
                ('contact_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre completo')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular')),
                ('contact_address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección física')),
                ('contact_social', models.URLField(blank=True, null=True, verbose_name='Red social / Web')),
                ('contact_email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Correo electrónico')),
                ('contact_job_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo / Profesión')),
                ('contact_company', models.CharField(blank=True, max_length=100, null=True, verbose_name='Empresa')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
            options={
                'db_table': 'CartItem',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
