# Generated by Django 5.1.7 on 2025-12-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='additional_info',
            field=models.TextField(blank=True, null=True, verbose_name='Información Adicional'),
        ),
    ]
