# Generated by Django 4.2.15 on 2025-12-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem_additional_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='is_sample',
            field=models.BooleanField(default=False, verbose_name='Es muestra'),
        ),
    ]
