# Generated by Django 5.1.7 on 2025-11-29 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cartitem_file_a_alter_cartitem_file_b_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='file_a',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='file_b',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='design_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='designs/%Y/%m/%d/'),
        ),
    ]
