# Generated by Django 4.2.15 on 2025-12-03 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cartitem_options_remove_cartitem_file_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='contact_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección física'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='contact_company',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Correo electrónico'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='contact_job_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo / Profesión'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='contact_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre completo'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='contact_social',
            field=models.URLField(blank=True, null=True, verbose_name='Red social / Web'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='logo_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='logos/%Y/%m/%d/', verbose_name='Logo de empresa'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.CharField(blank=True, choices=[('100', '100'), ('200', '200'), ('250', '250'), ('500', '500'), ('1000', '1000'), ('1500', '1500'), ('2000', '2000'), ('2500', '2500'), ('3000', '3000'), ('4000', '4000'), ('5000', '5000'), ('10000', '10000'), ('15000', '15000'), ('20000', '20000'), ('30000', '30000'), ('50000', '50000')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='size',
            field=models.CharField(blank=True, choices=[('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5'), ('A6', 'A6'), ('A7', 'A7'), ('medio-oficio', 'Medio oficio'), ('oficio', 'Oficio'), ('carta', 'Carta'), ('4x8', '4 x 8'), ('5x10', '5 x 10'), ('5x14', '5 x 14'), ('5x17', '5 x 17'), ('3x5', '3 x 5'), ('10x14', '10 x 14'), ('10x17', '10 x 17'), ('10x21', '10 x 21'), ('14x21', '14 x 21')], max_length=20, null=True),
        ),
    ]
