# Generated by Django 4.2.15 on 2025-12-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_cartitem_logo_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='logo_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='logos/%Y/%m/%d/', verbose_name='Logo de empresa'),
        ),
    ]
