# Generated by Django 4.2.15 on 2025-12-07 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='color_image_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de imagen del color'),
        ),
    ]
