# Generated by Django 4.2.15 on 2025-11-26 22:50

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stickers_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('shipping_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('email', models.EmailField(blank=True, max_length=250, verbose_name='Correo electrónico')),
                ('last_four', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('shipping_address', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_address1', models.CharField(blank=True, max_length=100, null=True)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_department', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_province', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_district', models.CharField(blank=True, max_length=100, null=True)),
                ('reason', models.CharField(blank=True, default='', max_length=400, null=True)),
                ('status', models.CharField(choices=[('recibido_pagado', 'Recibido y pagado'), ('recibido_no_pagado', 'Recibido pero no pagado'), ('en_proceso', 'En proceso'), ('en_camino', 'En camino'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado por no pagar')], default='recibido_pagado', max_length=20)),
                ('comments', models.CharField(blank=True, default='', max_length=400, null=True)),
                ('cupon', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.cupons')),
            ],
            options={
                'db_table': 'Order',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sku', models.CharField(max_length=20)),
                ('quantity', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='PEN Price')),
                ('file_a', models.FileField(blank=True, null=True, upload_to='files')),
                ('file_b', models.FileField(blank=True, null=True, upload_to='files')),
                ('comment', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
            options={
                'db_table': 'OrderItem',
            },
        ),
        migrations.CreateModel(
            name='OrderSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Order Summary',
                'verbose_name_plural': 'Orders Summary',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('order.order',),
        ),
    ]
